### ISSUE TITLE
The readme needs a little howto

### ISSUE THREAD

**Issue by kaleissin** [matthiask/django-translated-fields#1]
I don't easily see from the fields-code how to use the field. Could you add a little howto?  What to put into the field, how to get the data back out?

**Comment by matthiask** [comment]
Will do!

**Comment by matthiask** [comment]
@kaleissin I added some docs, feedback is very welcome!

**Comment by kaleissin** [comment]
Now even "monday brain pre caffeine" can understand it!

How does it work together with migrations though, if you decide to change settings.LANGUAGES?  Just run "makemigrations"? Adding more to LANGUAGES after a while isn't that uncommon.

**Comment by matthiask** [comment]
Yeah, you have to run makemigrations and migrate again.

**Comment by matthiask** [comment]
I expanded the model field description a bit: https://github.com/matthiask/django-translated-fields/compare/0.3...71d3b1c
