### ISSUE TITLE
Release a django app with translated fields as an option

### ISSUE THREAD

**Issue by raratiru** [matthiask/django-translated-fields#16]
This is not actually an issue, rather than a theoretical question with big practical impact, inspired from [this](https://github.com/matthiask/django-translated-fields/issues/7#issuecomment-457240936) strategic [choice](https://406.ch/writing/low-maintenance-software/):

> This package does not support adding translation functionality "from the outside" because that's exactly the thing which makes django-modeltranslation's code so brittle and costly to maintain.

My "about-to-be-released on github" django app creates a table like the following:
```python
from django.db import models 


class TheFollowing(models.Model):
    blah = models.TextField()

```
How can I provide the option of using `django-translated-fields`, if the user who installs my app wants the new field translated? The idea is to also cater for another user who does not want or need any translation happening out of the box.

Is this programmatically feasible or is it better to release two apps, one with translated field and one without?

**Comment by matthiask** [comment]
You could do something like this:

```
class TheFollowingBase(models.Model):
    # common functionality...

    class Meta:
        abstract = True



try:
    from translated_fields import TranslatedField
except ImportError:
    class TheFollowing(TheFollowingBase):
        blah = models.TextField()
else:
    class TheFollowing(TheFollowingBase):
        blah = TranslatedField(models.TextField())
```

Maybe there is a way to write a custom manager and common helpers so that the rest of the code works as-is. If you start filtering or searching the `blah` field you'd have to check whether you should be filtering `blah_<language>` or `blah` everywhere and this may become ugly quickly.

That being said, would it be so bad to just always depend on django-translated-fields and make the app only add one field behind the scenes if you're not using it resp. if there is only one language on the site? It might be mostly invisible especially if you're not using the `TranslatedFielAdmin` mixin.

**Comment by raratiru** [comment]
Thank you for the code layout it is very helpful. 

> That being said, would it be so bad to just always depend on django-translated-fields and make the app only add one field behind the scenes if you're not using it resp. if there is only one language on the site?

Indeed it would not be a problem, and this is a very good idea, thank you again!

**Comment by raratiru** [comment]
I am leaning towards the try-except approach for this occasion.

```python
try:
    from translated_fields import TranslatedField
except ImportError:
    class TheFollowing(TheFollowingBase):
        blah = models.TextField()
else:
    class TheFollowing(TheFollowingBase):
        blah = TranslatedField(models.TextField())
```
However, coverage, reports some of those statements as untested, in `forms.py` [-thank you for this solution-](https://github.com/matthiask/django-translated-fields/issues/10#issuecomment-460658781), `models.py` and `admin.py`. 

Running the test suite twice, once with `django-translated-fields` installed and once without it, all tests pass successfully. 

I have great difficulty in combining them in order to avoid coverage below 100%.

**Comment by uri-rodberg** [comment]
@raratiru I don't think you should release two apps, one with translated field and one without. Release one app in which you either always use django-translated-fields (which I think is better) or try to import it with an exception handler as @matthiask suggested.

**Comment by raratiru** [comment]
@uri-rodberg Thank you for the answer, indeed I will use the exception handler. 

I could not manage to achieve 100% coverage with one test suite execution. It seems to be possible, however, for coverage to aggregate reports and it feels like this is a good solution.

**Comment by raratiru** [comment]
Thank you for your help and inspiration. 

Finally `django-translated-fields` is a dependency of [`django-letsagree`](/raratiru/django-letsagree).
