### ISSUE TITLE
Possible to use .values and .values_list ?

### ISSUE THREAD

**Issue by cristianocca** [matthiask/django-translated-fields#19]
Right now, trying to call .values or .values_list on a translated field (by its name without _lang code) will result in a crash. I'm wondering if it is possible easily work around this problem to keep using those functions.

**Comment by cristianocca** [comment]
Not sure if possible for this to be implemented within the library in a way it works transparently with values and values list, but here's a work around that could be used in a values and values_list override. This is for just one field, but could be generalized.

```
lan = get_language()
field = ('text_%s' % lan) if lan else 'text_en'    # default language read from somewhere
return qs.values(text=F(field), *other_fields_without_text)
```

**Comment by matthiask** [comment]
The `translated_fields.to_attribute` helper helps with finding the field name in the database.

Not supporting queryset methods (`filter` would also be a candidate) transparently is a design decision: https://github.com/matthiask/django-translated-fields#other-features -- I could in principle be convinced to add helpers and utilities to make it easier to do what you're trying to do, however supporting this transparently is quite surely out of scope.

That being said, wouldn't you use something like this? (completely untested)

```
fields = ["text", ...]
return qs.annotate(**{field: F(to_attribute(field)) for field in fields}).values("...", *fields)
```

**Comment by cristianocca** [comment]
You are right, I've totally overlooked the to_attribute helper. 

I'm wondering what would be the best way to do this? Should it be something like providing a custom QuerySet class that overrides some methods?

**Comment by matthiask** [comment]
That would be possible but it's not a thing which necessarily has to be part of django-translated-fields since it might be brittle and/or hard to maintain. We would need more introspection for this and wrap all queryset methods with our own, and that (in my opinion) is exactly the thing which makes django-modeltranslation so impressive but also laborious to maintain.

**Comment by matthiask** [comment]
I/we should add some documentation since this may be a common question.
