### ISSUE TITLE
Fallback for locales like Django does (fr_fr to fr ?)

### ISSUE THREAD

**Issue by gilou** [matthiask/django-translated-fields#20]
Hi,

If I set up TranslatedFields using `LANGUAGES = [('fr', 'French'), ('en' , 'English')]`, and I define the `LANGUAGE_CODE` as fr-fr or en-us, the default configuration fails to find the attributes (looking for attr_fr_fr or attr_en_us, thus, failing).

The default behavior for i18n is usually to try the more specific language and then the more generic one, but as I read about your way of handling your dev (that I quite embrace and like :)) I wonder if it's on purpose or not!

What would be nice here, is to have something similar to gettext way, i.e. looking for attribute_fr_fr and if not found, fall back to attribute_fr. I'm willing to give it a try myself but I don't want to start hacking if you don't like the idea.

Regards,
Gilou

**Comment by matthiask** [comment]
I had the impression that when using `LocaleMiddleware`, `translation.get_language()` never returns a language code which isn't part of `LANGUAGES`, so I don't see how the `fr-fr` case can happen at all?

I'm also not completely sure what you're proposing. Are you proposing a custom `attrgetter` (and maybe `attrsetter`) with the fallback behavior?

Thanks for the kind words :-)

**Comment by gilou** [comment]
Hmm, no, LANGUAGE_CODE is just the default, LANGUAGES is a filter for what you can select, so if I have fr in LANGUAGES (as in, allow any fr_* for selection), it will work.
```
LANGUAGE_CODE = 'fr-fr'
LANGUAGES = [('fr', 'French'), ('en' , 'English')]
```
Django is fine with it, uses the fr translations when fr_FR isn't available, as stated in https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#how-django-discovers-language-preference

> If a base language is available but the sublanguage specified is not, Django uses the base language. For example, if a user specifies de-at (Austrian German) but Django only has de available, Django uses de.

However, using a TranslatedField, it uses the LANGUAGES directly, so fields are named field_fr (which is fine), but since you ask for LANGUAGE_CODE, you try to use field_fr_fr. Which is not so fine, and obviously it fails: `'Question' object has no attribute 'question_fr_fr'`

I'm not familiar with your code, but I'm guessing either I can override the getter/setter, or.. simply ignore that and just tag all my fields with _fr_fr !

The nice way would be the Django way, i.e. look for _fr_fr and falling back to _fr if it's not there

**Comment by matthiask** [comment]
Well, writing a getter shouldn't be that hard (maybe ugly, definitely untested):

```
from django.utils.translation import get_language
from translated_fields import to_attribute

def attrgetter(name, field):
   def getter(self):
        language = get_language()
        f= to_attribute(name)
        value = getattr(self, f, None)
        if value is not None:
            return value
        f = to_attribute(name, language.split("-")[0])
        return getattr(self, f, None)

    return getter
```

Then, use `TranslatedField(..., attrgetter=attrgetter)` when declaring the model.
