### ISSUE TITLE
contextvars and immutables - required but not documented

### ISSUE THREAD

**Issue by uri-rodberg** [matthiask/django-translated-fields#23]
Upgrading `django-translated-fields` to 0.10.2 (from 0.9.0) with pip installs also `contextvars-2.4` and `immutables-0.14`, but I didn't find it documented in `README.rst` and `CHANGELOG.rst`. Are `contextvars` and `immutables` required and what is the cause for this change?

**Comment by matthiask** [comment]
The contextvars library is only installed from PyPI on Python<3.7. It is a builtin library in Python 3.7 and higher. https://docs.python.org/3/library/contextvars.html

The contextvars library depends on immutables.

The context variable is used to modify the behavior of `Field.verbose_name`: When `_show_language_code` is set, `Field.verbose_name` returns not only the verbose name of the field but also the language code in square brackets. (https://github.com/matthiask/django-translated-fields/blob/3383755b786dd51c2e2314e444cc640136cb3985/translated_fields/fields.py#L24)

https://github.com/matthiask/django-translated-fields/blob/master/CHANGELOG.rst (first 0.10 entry)

**Comment by uri-rodberg** [comment]
I understand. We are using Python 3.6. Thank you for documenting this.

**Comment by matthiask** [comment]
Thanks for the report :)
