### ISSUE TITLE
not works with search_fields

### ISSUE THREAD

**Issue by summonerriftofficial** [matthiask/django-translated-fields#28]
is there any chance to support searching the key directly

// Works
    `search_fields = ('name_en','name_de', 'key')`
// Not Works
   ` search_fields = ('name', 'key')`

**Comment by matthiask** [comment]
No, since `name` isn't a real field, just a descriptor.

You can write `search_fields = [*Model.name.fields, "key"]` if you want to automatically include all concrete fields.

The rationale for this design decision is here: https://github.com/matthiask/django-translated-fields#other-features

**Comment by ahmedsafadii** [comment]
Thank you <3

how i can buy you a coffe for this great pip.
