### ISSUE TITLE
filter is not working for the main name

### ISSUE THREAD

**Issue by ahmedsafadii** [matthiask/django-translated-fields#29]
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: city_id, country, created, daily, hourly, id, latitude, longitude, name_ar, name_de, name_en, name_es, name_fr, name_it, name_nl, name_ru, name_sv, name_tr, name_ua, name_zh_cn, name_zh_tw, state, updated, users, weather

`cities.filter(name="test")`

any idea to search over all languages with the same key name?

**Comment by matthiask** [comment]
Yes, that's by design.

You could do something like this:

```python
from translated_fields import to_attribute

cities.filter(**{to_attribute("name"): "test"})
```

(See here for the reasoning https://github.com/matthiask/django-translated-fields#other-features)

**Comment by ahmedsafadii** [comment]
Thank you for answering 

if i want use the functions of the field 

contains

example

```
            kwargs = {
                f"name_{language}__icontains": name,
                f"name_en__icontains": name
            }
            cities = cities.filter(**kwargs)
```

**Comment by ahmedsafadii** [comment]
Thank you for your hard works <3

**Comment by matthiask** [comment]
I'll assume that you have found a solution which works for you. I re-read your initial question again and there's a way to do this as well, for example as follows:

```python
from django.db.models import Q
q = Q{**{City.name.fields[0]: "test"})
for field in City.name.fields[1:]:
    q |= Q(**{field: "test"})
cities.filter(q)
```

The idea is to generate a `Q()` object for each language's name field and OR them together (`q | q`)

```

**Comment by Zerotask** [comment]
I also stumbled upon this and we ended using the suggested solution from [here](https://github.com/matthiask/django-translated-fields/issues/29#issuecomment-1151238439). Would be great to have this added to the documentation. :)

**Comment by matthiask** [comment]
Makes sense. I have added an example to the docs, see https://github.com/matthiask/django-translated-fields/commit/47f40f7d933079de0642caafd53f9e36f41d3455
