### ISSUE TITLE
Passing fields from one instance to another

### ISSUE THREAD

**Issue by 125ade** [matthiask/django-translated-fields#30]
trying to create an instance of a model and passing to it some fields of another model (all fields passed use "TranslatedField") only the current language is passed and not the current language + the other fields with the other languages

```
# model
class FirstModel(models.Model):
    name = TranslatedField(models.CharField(  _("name"), max_length=200, default="text"),)
    description = TranslatedField(models.TextField(  _("description"), blank=True,  null=True, default="text" ),)

class SecondModel(models.Model):
    name = TranslatedField(models.CharField(  _("name"), max_length=200, default="text"),)
    description = TranslatedField(models.TextField(  _("description"), blank=True,  null=True, default="text" ),)

# the code that make problem
istance_of_second_Model.description = istance_of_first_Model.description
```

only one of the fields generated by TranslatedField is passed to the second model and is that of the current language while my goal is to pass "simultaneously" all the fields of all languages

in the documentation I do not understand how to solve this problem, I also tried various approaches but I could not solve for this reason I try to write the problem here

**Comment by 125ade** [comment]
```
def set_all_fields(name, field):
    def setter(self, value):
        for field in field.fields:
            setattr(self, field, value)
    return setter
```

it seems this will help me (taken from the documentation) but I can't figure out how to adapt the function to my specific problem

**Comment by matthiask** [comment]
You could do something like this:

```
def copy_translated_values(from_, to_, field_name):
    field = getattr(from_, field_name)
    for f in field.fields:
        setattr(to_, f, getattr(from_, f))

copy_translated_values(first_instance, second_instance, "description")
```

`FirstModel.description.fields` contains a list of all translated fields and you could take advantage of this.

**Comment by 125ade** [comment]
Thank you very much! this function solves the issue I have opened

**Comment by matthiask** [comment]
Great!
