### ISSUE TITLE
Auto-Detection of Current Language for list_filter in django-translated-fields

### ISSUE THREAD

**Issue by summonerriftofficial** [matthiask/django-translated-fields#33]
Hello,

I have been using django-translated-fields in my projects and I have found it to be a very useful package. Recently, I've come across a potential area of improvement related to the language specification.

In my current setup, I define the 'list_display' field like this:

```python
list_display = ["id", "name"]
```

This approach automatically detects and applies the current language for displaying strings, which works perfectly. 

However, when it comes to the 'list_filter' field, I haven't found a way to automatically set the language:

```python
list_filter = ["status", "par_type_en_us"]
# or
list_filter = ["status", *Champion.par_type.fields]
```

As you can see, I currently need to manually specify the language ('en_us' in this case) or expand the fields, which isn't ideal.

I am wondering whether there might be a way to incorporate a feature that would automatically detect the current language for the 'list_filter' field, just as it does for 'list_display'? I believe this would make the package even more intuitive and user-friendly.

I look forward to your feedback and potential solutions to this.

Thank you!

**Comment by matthiask** [comment]
Hi

You can achieve something like this using:

```python
def get_list_filter(self, request):
    from translated_fields import to_attribute # maybe import this at the top of the file
    return ["status", to_attribute("par_type")]
```

I have avoided any automatisms until now, the rationale for this is here: https://github.com/matthiask/django-translated-fields#other-features

It's not obvious to me if `list_display=["status", "par_type"]` should be expanded to all `par_type` fields or only the `par_type` field in the current language. Also, the current language in the admin panel may not be the one you're interested in when editing content. My thinking is that it's simpler to leave the legwork to implement the desired functionality to users of the library. (At least if nobody comes up with a good naming scheme.)

Thanks!

**Comment by summonerriftofficial** [comment]
Works, Thank you.
