### ISSUE TITLE
Order by automcailly

### ISSUE THREAD

**Issue by ahmedsafadii** [matthiask/django-translated-fields#34]
Thank you for this great package, 

I was wondering how I can do order_by on filter

def to_representation(self, instance):
       categories = CategorySerializer(Category.objects.all().order_by('name'), many=True).data - True
       categories = CategorySerializer(Category.objects.all().order_by('name_en'), many=True).data - False

**Comment by matthiask** [comment]
Hey

You can use `translated_fields.to_attribute("name")` if you need the name field for the current language. I hope that helps!

**Comment by ahmedsafadii** [comment]
> Hey
> 
> You can use `translated_fields.to_attribute("name")` if you need the name field for the current language. I hope that helps!

Would you please apply it for the following orm

Category.objects.all().order_by('name')

**Comment by matthiask** [comment]
No, the reason why not is mentioned here: 
https://github.com/matthiask/django-translated-fields#other-features

Thanks!
