### ISSUE TITLE
Django versions supported

### ISSUE THREAD

**Issue by uri-rodberg** [matthiask/django-translated-fields#36]
Which versions of Django are supported? And is it possible to specify them on PyPI? I noticed that other packages on PyPI specify which versions of Django are supported.

**Comment by matthiask** [comment]
All versions from 3.2 to the current development version are/should be supported. 

I find keeping the Trove identifiers a bit annoying and I'm trying to avoid doing the extra work. I should still specify the versions somewhere if not there.

**Comment by uri-rodberg** [comment]
Thank you.
