### ISSUE TITLE
[Question] Is is possible to translate Django's Permission model (the name)

### ISSUE THREAD

**Issue by gabn88** [matthiask/django-translated-fields#7]
I know the issue tracker is not always the right place for a question, but we would like to migrate our app that uses django-modeltranslation to Django version 2.1. Since modeltranslations is currently unmaintained, and only support Django 1.11 (more or less), we are thinking about using this package.

I think it has everything we need (apart maybe from some glue code which is easy to create), except support for multi-language permissions (contrib.auth.model.Permission.name), am I correct?

Do you maybe have any idea how to circumvent this issue?

**Comment by matthiask** [comment]
Great!

This package does not support adding translation functionality "from the outside" because that's exactly the thing which makes django-modeltranslation's code so brittle and costly to maintain. 

I see several possibilities:

- Not use those permissions at all (probably not workable)
- Use your own model with a OneToOneField to auth.Permission which contains the necessary translations and monkey patch Permission's `__str__` method. Might be costly because of the additional join involved.
- Add fields to auth.Permission (`Permission.add_to_class("name_en", CharField(_("english name"), max_length=??))`) and monkey patch `__str__` again. If you follow this route you should add the `auth` app to Django's `MIGRATION_MODULES` so that your changes are picked up. This may make upgrading Django a bit harder, because you'll have to apply eventual changes to the auth models yourself.

It may be useful to use `translated_attrgetter` for providing the monkey patch (`Permission.__str__ = translated_fields.fields.translated_attrgetter("name")`) but this does not help much in any case.

All of those possibilities are hacky, but so is django-modeltranslation.

**Comment by gabn88** [comment]
Thank you! I will definitely go with option 3, since we already have the required database columns (name_en, name_de, etc) thanks to django-modeltranslations.

I'm not really familiar with monkey-patching an existing model. How do I make sure the patch is applied correctly? Make a new module with models.py and apply the patch there? Migrations would get there too, or would they be in Django's contrib.auth.models folder, like where they are now?

If we can leave this issue open for a few weeks I can keep track of my progress and the pittfalls here if there are others with the same issue, if that is okay with you?

**Comment by matthiask** [comment]
> I'm not really familiar with monkey-patching an existing model. How do I make sure the patch is applied correctly? Make a new module with models.py and apply the patch there? Migrations would get there too, or would they be in Django's contrib.auth.models folder, like where they are now?
> 

Yeah, I'd put those statements into a models.py file in your project... somewhere where it fits. You "just" have to make sure that the code is executed while loading the models, otherwise you'll get strange errors.

The `MIGRATION_MODULES` part might not be necessary, respectively since you're using django-modeltranslation you should already have a custom place where your `django.contrib.auth` migrations live -- otherwise, how would the additional columns even exist in the database?

> If we can leave this issue open for a few weeks I can keep track of my progress and the pittfalls here if there are others with the same issue, if that is okay with you?

Sure!

**Comment by gabn88** [comment]
First try (will update this post as we go):

- Install django-translated-fields, remove django-modeltrans 
- Add the following code to a new module called translated_fields_perm (also add to INSTALLED_APPS):

```
from django.contrib.auth.models import Permission
from django.conf import settings
from django.db.models import CharField
from django.utils.translation import ugettext_lazy as _

from translated_fields import fields

for index, language_code in enumerate([l[0] for l in settings.LANGUAGES]):
    Permission.add_to_class("name_"+language_code, CharField(_("Name ["+language_code+"]"), max_length=255))

Permission.__str__ = fields.translated_attrgetter("name")
```

- Remove modeltranslation from INSTALLED_APPS.
- Add to all  the translatable fields: TranslatedField(... Old model Field ...)
- Replace all TranslationAdmin by TranslatedFieldAdmin
- Update forms with the following code (I took name as example, this form only shows the users language):

```
class MyForm(ModelForm):
    class Meta:
        fields = ['name_'+ x.replace('-','_') for x in settings.SELECTABLE_LANGUAGES] + [... other fields ...]

    def __init__(self, *args, **kwargs):
        language = get_language()
        for selectable_language in settings.SELECTABLE_LANGUAGES:

            if selectable_language == language:
                pass
            else:
                self.fields['name_{language}'.format(language=selectable_language)].widget = forms.HiddenInput()
                # We could also delete the field, or create the field list dynamically. Will update the code if necessary
```
OR if you want all the fields with an (JS/CSS enabled) 'more languages' button:
```
class MyForm(ModelForm):
    class Meta:
        fields = [['name_'+ x.replace('-','_') for x in settings.SELECTABLE_LANGUAGES], ... other fields ...]

    def __init(self, *args, **kwargs):
        for selectable_language in settings.SELECTABLE_LANGUAGES:
            if selectable_language == language:
                selectable_language = selectable_language.replace('-', '_')
                self.fields['name_{language}'.format(language=selectable_language)].required=True
    
 self.fields['name_{language}'.format(language=selectable_language)].widget.attrs.update({'class':'language-active form-control'})
            else:
                selectable_language = selectable_language.replace('-', '_')
                self.fields['name_{language}'.format(language=selectable_language)].required=False
                self.fields['name_{language}'.format(language=selectable_language)].widget.attrs.update({'class':'language-not-active form-control'})
```
- Change the FilterSets where translated fields are used... coming soon!

**Comment by gabn88** [comment]
I think I really need some help now.

Most things are working, except for Django rest framework viewsets. 
It raises on GETting:
`Cannot resolve keyword 'name' into field. Choices are: name_de, name_en, name_en_gb, name_es, name_fi, name_fr, name_it, name_nl, name_zh_hans`

Full traceback:
http://dpaste.com/1JE7RWC# (will expire in one day, because there are some business things included).

I have tried to change the TranslatedFieldValidatorMixin to make it work, but that fails. Maybe a viewset mixin could work, but I've spitted through all the code and did not find the solution yet. I will dedicate some more time to this tomorrow.

**Comment by matthiask** [comment]
django-modeltranslation leaves the original `name` field around. django-translated-fields does not add a `name` field at all -- `name` in this case is "just" a descriptor (a property if you are unsure what a Python descriptor is)

Probably the rest framework viewset still expects a `name` field somewhere? I'm not sure where the `TranslatedFieldValidatorMixin` comes from, can you show the code of this mixin and/or of the rest framework viewset?

**Comment by gabn88** [comment]
I have the ‘name’ in my fields list, because I want to be able to get and set ‘name’ and that it automatically picks the current language. Maybe a specific serializerField is better then the mixin. Will try that route! Thanks!

The mixin is shared one post higher.


Op 26 jan. 2019 om 11:49 heeft Matthias Kestenholz <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


django-modeltranslation leaves the original name field around. django-translated-fields does not add a name field at all -- name in this case is "just" a descriptor (a property if you are unsure what a Python descriptor is)

Probably the rest framework viewset still expects a name field somewhere? I'm not sure where the TranslatedFieldValidatorMixin comes from, can you show the code of this mixin and/or of the rest framework viewset?

**Comment by matthiask** [comment]
Ah yes, sorry. I overlooked it. I can't help you much with the rest framework integration, I'm no heavy user of it (yet?)

**Comment by gabn88** [comment]
No problem, I found the issue. It was deep-down in my own code, and it was trivial to fix when I found the issue. I will test for a few days, but it seems to me that my post above describes how to do a full migration from django-modeltranslateion to django-translated-fields :smile:

**Comment by gabn88** [comment]
Hi!
Since the new release (0.8), the Permission.__str__ = fields.translated_attrgetter("name") is giving me the error: TypeError: Translated_attrgetter() missing 1 required positional argument: 'field'. 

Is there a quick fix for this?

I'm still using the old 0.7.2 until I have time to look into this, but maybe you know a fix so we can stay up-to-date. And it is also nice to mention it in this thread I think :)

**Comment by matthiask** [comment]
Oh I'm sorry for breaking your code!

Something like the following should work:

```
Permission.__str__ = lambda self: getattr(
    self, 
    to_attribute("name", language=get_language() or settings.LANGUAGES[0][0]
)
```

**Comment by gabn88** [comment]
Thanks a lot! It is working :)

**Comment by gabn88** [comment]
On another note: 

```for language_code, dummy in settings.LANGUAGES:
    Permission.add_to_class(to_attribute("name", language_code), CharField(
        _("Name [" + language_code + "]"), max_length=255, blank=True, default=''))
```
adds a migration file every time I run manage.py makemigrations.
Is there a way to circumvent this that you know of?

**Comment by matthiask** [comment]
The `_("Name [" + language_code + "]")` will probably not work the way you want it to. The translation strings "Name [en]", "Name [other]" will not be picked up by `makemessages`.

I'd recommend using only `_("name")` as `verbose_name` and maybe use the `TranslatedFieldAdmin` if you want to see the fields' language code in the administration interface.

**Comment by gabn88** [comment]
Sorry for the late reply, I first wanted to test your solution thoroughly. However, it seems that it does not matter what I make for the verbose name. It seems that the for loop (so the 'dynamic' generation of the extra fields) is the culprit. 

```
for language_code, dummy in settings.LANGUAGES:
    Permission.add_to_class(to_attribute("name", language_code), CharField(
        _("name"), max_length=255, blank=True, default=''))
```

**Comment by gabn88** [comment]
The final code that does not generate migrations on every makemigration:

```
in models.py:

Permission.__str__ = lambda self: getattr(
    self,
    to_attribute("name", language_code=get_language() or settings.LANGUAGES[0][0]
                 ))

for language_code, dummy in settings.LANGUAGES:
    if not hasattr(Permission, to_attribute("name", language_code)):
        field = CharField(
            _("name") + ' [' + language_code + ']', max_length=255, blank=True, default='')
        Permission.add_to_class(
            to_attribute("name", language_code), field)
```
And in migrations/0001_initial.py:

```
import django.contrib.auth.models
from django.contrib.auth import validators
from django.db import migrations, models
from django.utils import timezone

TARGET_APP = 'auth'


class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        # overriding application operated upon
        super(Migration, self).__init__(name, TARGET_APP)

    replaces = (
        (TARGET_APP, '0001_initial'),)

    dependencies = [
        ('contenttypes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(verbose_name='ID',
                                        serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('content_type', models.ForeignKey(
                    to='contenttypes.ContentType',
                    on_delete=models.CASCADE,
                    to_field='id',
                    verbose_name='content type',
                )),
                ('codename', models.CharField(
                    max_length=100, verbose_name='codename')),
            ],
            options={
                'ordering': ('content_type__app_label', 'content_type__model', 'codename'),
                'unique_together': {('content_type', 'codename')},
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(verbose_name='ID',
                                        serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True,
                                          max_length=80, verbose_name='name')),
                ('permissions', models.ManyToManyField(
                    to='auth.Permission', verbose_name='permissions', blank=True)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID',
                                        serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    default=timezone.now, verbose_name='last login')),
                ('is_superuser', models.BooleanField(
                    default=False,
                    help_text='Designates that this user has all permissions without explicitly assigning them.',
                    verbose_name='superuser status'
                )),
                ('username', models.CharField(
                    help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True,
                    max_length=30, verbose_name='username',
                    validators=[validators.UnicodeUsernameValidator()],
                )),
                ('first_name', models.CharField(max_length=30,
                                                verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30,
                                               verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=75,
                                            verbose_name='email address', blank=True)),
                ('is_staff', models.BooleanField(
                    default=False, help_text='Designates whether the user can log into this admin site.',
                    verbose_name='staff status'
                )),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='active', help_text=(
                        'Designates whether this user should be treated as active. Unselect this instead of deleting '
                        'accounts.'
                    )
                )),
                ('date_joined', models.DateTimeField(
                    default=timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(
                    to='auth.Group', verbose_name='groups', blank=True, related_name='user_set',
                    related_query_name='user', help_text=(
                        'The groups this user belongs to. A user will get all permissions granted to each of their '
                        'groups.'
                    )
                )),
                ('user_permissions', models.ManyToManyField(
                    to='auth.Permission', verbose_name='user permissions', blank=True,
                    help_text='Specific permissions for this user.', related_name='user_set',
                    related_query_name='user')
                 ),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='permission',
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='name_de',
            field=models.CharField(
                max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='permission',
            name='name_en',
            field=models.CharField(
                max_length=255, null=True, verbose_name='name'),
        ),
        .... ETC for other languagues ....
    ]
```

No need for MIGRATION_MODULES in settings.py.
This is working great for me :)
